version: "3.2"

services:
  application:
    ports:
    - 8080:8080
    build:
      context: .
      dockerfile: ./application/Dockerfile
    volumes:
      - ./common:/code/common
      - ./application:/code/application
    command: flask run -h0.0.0.0 -p8080
    environment:
      FLASK_APP: "application.app"
      FLASK_ENV: "development"
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    volumes:
      - ./common:/code/common
      - ./worker:/code/worker
    ports:
    - 8081:8081
    environment:
      FLASK_APP: "worker.app"
      FLASK_ENV: "development"
    command: flask run -h0.0.0.0 -p8081